RTLSDR Airband advanced mode

diff --git a/rootfs/etc/cont-init.d/02-rtl_airband b/rootfs/etc/cont-init.d/02-rtl_airband
--- a/rootfs/etc/cont-init.d/02-rtl_airband
+++ b/rootfs/etc/cont-init.d/02-rtl_airband
@@ -1,47 +1,51 @@
 #!/usr/bin/with-contenv sh
 # shellcheck shell=sh
 
-sed -i "s/type = \"[^<]*\"; # device 1 radio/type = \"$STATION1_RADIO_TYPE\"; # device 1 radio/g" /usr/local/etc/rtl_airband.conf
-sed -i "s/gain = [^<]*; # device 1/gain = $STATION1_GAIN; # device 1/g" /usr/local/etc/rtl_airband.conf
+if [ -z "$RTLSDRAIRBAND_CUSTOMCONFIG" ]; then
+	sed -i "s/type = \"[^<]*\"; # device 1 radio/type = \"$RTLSDRAIRBAND_RADIO_TYPE\"; # device 1 radio/g" /usr/local/etc/rtl_airband.conf
+	sed -i "s/gain = [^<]*; # device 1/gain = $RTLSDRAIRBAND_GAIN; # device 1/g" /usr/local/etc/rtl_airband.conf
 
-if [ -n "${STATION1_CORRECTION}" ]; then
-	sed -i "s/#correction = [^<]*; # device 1/correction = $STATION1_CORRECTION; # device 1/g" /usr/local/etc/rtl_airband.conf
-fi
+	if [ -n "${RTLSDRAIRBAND_CORRECTION}" ]; then
+		sed -i "s/#correction = [^<]*; # device 1/correction = $RTLSDRAIRBAND_CORRECTION; # device 1/g" /usr/local/etc/rtl_airband.conf
+	fi
 
-if [ -n "${STATION1_LABELS}" ]; then
-	sed -i "s/#labels = ([^<]*); # device 1/labels = ( $STATION1_LABELS ); # device 1/g" /usr/local/etc/rtl_airband.conf
-fi
+	if [ -n "${RTLSDRAIRBAND_LABELS}" ]; then
+		sed -i "s/#labels = ([^<]*); # device 1/labels = ( $RTLSDRAIRBAND_LABELS ); # device 1/g" /usr/local/etc/rtl_airband.conf
+	fi
 
-if [ -n "${STATION1_SHOWMETADATA}" ]; then
-	sed -i "s/send_scan_freq_tags = true; # device 1/#send_scan_freq_tags = true; # device 1/g" /usr/local/etc/rtl_airband.conf
-fi
+	if [ -n "${RTLSDRAIRBAND_SHOWMETADATA}" ]; then
+		sed -i "s/send_scan_freq_tags = true; # device 1/#send_scan_freq_tags = true; # device 1/g" /usr/local/etc/rtl_airband.conf
+	fi
 
-sed -i "s/mode = \"[^<]*\"; # device 1/mode = \"$STATION1_MODE\"; # device 1/g" /usr/local/etc/rtl_airband.conf
+	sed -i "s/mode = \"[^<]*\"; # device 1/mode = \"$RTLSDRAIRBAND_MODE\"; # device 1/g" /usr/local/etc/rtl_airband.conf
 
-# rtl_airband.conf for some reason has different config names for multichannel and scan modes
-# fix to get that working
+	# rtl_airband.conf for some reason has different config names for multichannel and scan modes
+	# fix to get that working
 
-if [ -z "${STATION1_FREQS}" ]; then
-	echo "Error! Frequency not set. Please set STATION1_FREQS. See https://github.com/fredclausen/docker-rtlsdrairband#rtlsdr-airband for details. Aborting!"
-	exit 1
-fi
+	if [ -z "${RTLSDRAIRBAND_FREQS}" ]; then
+		echo "Error! Frequency not set. Please set RTLSDRAIRBAND_FREQS. See https://github.com/fredclausen/docker-rtlsdrairband#rtlsdr-airband for details. Aborting!"
+		exit 1
+	fi
 
-if [ "$STATION1_MODE" = "scan" ]; then
-	sed -i "s/#freqs = ([^<]*); # device 1/freqs = ( $STATION1_FREQS ); # device 1/g" /usr/local/etc/rtl_airband.conf
+	if [ "$RTLSDRAIRBAND_MODE" = "scan" ]; then
+		sed -i "s/#freqs = ([^<]*); # device 1/freqs = ( $RTLSDRAIRBAND_FREQS ); # device 1/g" /usr/local/etc/rtl_airband.conf
+	else
+		sed -i "s/#freq = [^<]*; # device 1/freq = $RTLSDRAIRBAND_FREQS; # device 1/g" /usr/local/etc/rtl_airband.conf
+	fi
+
+	sed -i "s/server = \"[^<]*\"; # device 1/server = \"$RTLSDRAIRBAND_SERVER\"; # device 1/g" /usr/local/etc/rtl_airband.conf
+	sed -i "s/mountpoint = \"[^<]*\"; # device 1/mountpoint = \"$RTLSDRAIRBAND_MOUNTPOINT\"; # device 1/g" /usr/local/etc/rtl_airband.conf
+	sed -i "s/name = \"[^<]*\"; # device 1/name = \"$RTLSDRAIRBAND_NAME\"; # device 1/g" /usr/local/etc/rtl_airband.conf
+	sed -i "s/\\genre = \"[^<]*\"; # device 1/\\genre = \"$RTLSDRAIRBAND_GENRE\"; # device 1/g" /usr/local/etc/rtl_airband.conf
+	sed -i "s/username = \"[^<]*\"; # device 1/username = \"$RTLSDRAIRBAND_USERNAME\"; # device 1/g" /usr/local/etc/rtl_airband.conf
+	sed -i "s/password = \"[^<]*\"; # device 1/password = \"$RTLSDRAIRBAND_PASSWORD\"; # device 1/g" /usr/local/etc/rtl_airband.conf
+
+	# If serial not set, set the index to 0
+	if [ -z "${RTLSDRAIRBAND_SERIAL}" ]; then
+		sed -i "s/#index = \"[^<]*\"; # device 1/index = \"0\"; # device 1/g" /usr/local/etc/rtl_airband.conf
+	else
+		sed -i "s/#serial = \"[^<]*\"; # device 1/serial = \"$RTLSDRAIRBAND_SERIAL\"; # device 1/g" /usr/local/etc/rtl_airband.conf
+	fi
 else
-	sed -i "s/#freq = [^<]*; # device 1/freq = $STATION1_FREQS; # device 1/g" /usr/local/etc/rtl_airband.conf
-fi
-
-sed -i "s/server = \"[^<]*\"; # device 1/server = \"$STATION1_SERVER\"; # device 1/g" /usr/local/etc/rtl_airband.conf
-sed -i "s/mountpoint = \"[^<]*\"; # device 1/mountpoint = \"$STATION1_MOUNTPOINT\"; # device 1/g" /usr/local/etc/rtl_airband.conf
-sed -i "s/name = \"[^<]*\"; # device 1/name = \"$STATION1_NAME\"; # device 1/g" /usr/local/etc/rtl_airband.conf
-sed -i "s/\\genre = \"[^<]*\"; # device 1/\\genre = \"$STATION1_GENRE\"; # device 1/g" /usr/local/etc/rtl_airband.conf
-sed -i "s/username = \"[^<]*\"; # device 1/username = \"$STATION1_USERNAME\"; # device 1/g" /usr/local/etc/rtl_airband.conf
-sed -i "s/password = \"[^<]*\"; # device 1/password = \"$STATION1_PASSWORD\"; # device 1/g" /usr/local/etc/rtl_airband.conf
-
-# If serial not set, set the index to 0
-if [ -z "${STATION1_SERIAL}" ]; then
-	sed -i "s/#index = \"[^<]*\"; # device 1/index = \"0\"; # device 1/g" /usr/local/etc/rtl_airband.conf
-else
-	sed -i "s/#serial = \"[^<]*\"; # device 1/serial = \"$STATION1_SERIAL\"; # device 1/g" /usr/local/etc/rtl_airband.conf
+	echo "Custom config provided. Ignoring RTLSDIRBAND config options"
 fi
